// <auto-generated />
using System;
using DataAccessLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLibrary.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DataAccessLibrary.Model.StudentDropDown", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dept")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentModelId");

                    b.ToTable("studentDropDown");
                });

            modelBuilder.Entity("DataAccessLibrary.Model.StudentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dept")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("studentInfo");
                });

            modelBuilder.Entity("DataAccessLibrary.Model.StudentDropDown", b =>
                {
                    b.HasOne("DataAccessLibrary.Model.StudentModel", null)
                        .WithMany("Type")
                        .HasForeignKey("StudentModelId");
                });

            modelBuilder.Entity("DataAccessLibrary.Model.StudentModel", b =>
                {
                    b.Navigation("Type");
                });
#pragma warning restore 612, 618
        }
    }
}
